# Домашнее задание по теме: пакет `pandas` (основная информация)

## Подготовка окружения

In [1]:
# ВНИМАНИЕ: необходимо удостовериться, что виртуальная среда выбрана правильно!

!pip -V

pip 20.3.3 from /home/ira/anaconda3/envs/LevelUp_DataScience/lib/python3.8/site-packages/pip (python 3.8)

In [2]:
# !conda install pandas -y

In [3]:
import pandas as pd

pd.__version__

'1.2.1'

## Загрузка и изучение данных

In [4]:
wiki_page = "https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D1%8F%D0%B7%D1%8B%D0%BA%D0%BE%D0%B2_%D0%BF%D0%BE_%D0%BA%D0%BE%D0%BB%D0%B8%D1%87%D0%B5%D1%81%D1%82%D0%B2%D1%83_%D0%BD%D0%BE%D1%81%D0%B8%D1%82%D0%B5%D0%BB%D0%B5%D0%B9"

In [5]:
# прочитать данные из указанной wiki страницы с помощью `pandas`
# ВНИМАНИЕ: при чтении указать номер колонки с индексом = 0
df_info_list = pd.read_html(wiki_page, index_col=0)

In [6]:
# отобразить все прочитанные таблицы с веб-страницы
for index, df_from_page in enumerate(df_info_list):
    print(f"index = {index}")
    display(df_from_page)

index = 0

                         1
0
Состояние  отпатрулирована

index = 1

,Язык,Родной язык по версии Ethnologue[1],Основная страна,Количество стран
№,,,,
1,Китайский,1 296 461 000[2] — 1 311 000 000,Китай,39
2,Испанский,460 000 000,Испания,31
3,Английский,379 000 000,Великобритания,137
4,Хинди,341 000 000,Индия,4
5,Арабский,313 177 600[3] — 319 000 000,Саудовская Аравия,59
6,Бенгальский,228 000 000,Бангладеш,4
7,Португальский,221 000 000,Португалия,15
8,Русский,154 000 000,Россия,19
9,Японский,128 000 000,Япония,2
10,Лахнда (Западный панджаби),119 000 000,Пакистан,6
11,Маратхи,83 100 000,Индия,1
12,Телугу,82 000 000,Индия,2
13,Малайский,80 300 000,Малайзия,20
14,Турецкий,79 400 000,Турция,8
15,Корейский,77 300 000,Корея,6
16,Французский,77 200 000,Франция,54
17,Немецкий,76 100 000,Германия,28
18,Вьетнамский,76 000 000,Вьетнам,4
19,Тамильский,75 000 000,Индия,7
20,Урду,68 600 000,Пакистан,7
21,Яванский,68 300 000,Индонезия,3
22,Итальянский,64 800 000,Италия,14
23,Персидский,61 800 000,Иран,30
24,Гуджарати,56 400 000,Индия,7

index = 2

,Язык,Родной язык по версии Encarta[4],Средоточие,Территории распространения,Самоназвание(образец письменности)
№,,,,,
1,Китайский,1 212 560 000,Китай,"Китай, Тайвань, Сингапур, Малайзия","中文, 汉语"
2,Арабский,422 039 637,NaN,"страны Северной Африки, Саудовская Аравия, Ира...",العربية
3,Хинди,366 000 000,Индия,Индия,हिन्दी
4,Английский,341 000 000,Англия,"Великобритания, США, Канада, Австралия, Новая ...",English
5,Испанский,322 200 637,Испания,"Испания, Южная Америка (кроме Бразилии, Сурина...","Español, Castellano"
...,...,...,...,...,...
65,Чхаттисгархи,11 535 000,Индия,Индия,छत्तिसगढ़ी
66,Фула,11 428 700,Западная Африка,Западная Африка,"Pulaar, Fulfulde"
67,Дакхни[en],10 709 800,Индия,Индия,NaN
68,Малагасийский,10 484 000,Мадагаскар,Мадагаскар,Malagasy
69,Белорусский,10 200 000,Белоруссия,"Белоруссия, Польша",Беларуская мова

In [7]:
# получить dataframe с таблицей "Данные энциклопедии Encarta 2009 года"
df = df_info_list[2]

df

,Язык,Родной язык по версии Encarta[4],Средоточие,Территории распространения,Самоназвание(образец письменности)
№,,,,,
1,Китайский,1 212 560 000,Китай,"Китай, Тайвань, Сингапур, Малайзия","中文, 汉语"
2,Арабский,422 039 637,NaN,"страны Северной Африки, Саудовская Аравия, Ира...",العربية
3,Хинди,366 000 000,Индия,Индия,हिन्दी
4,Английский,341 000 000,Англия,"Великобритания, США, Канада, Австралия, Новая ...",English
5,Испанский,322 200 637,Испания,"Испания, Южная Америка (кроме Бразилии, Сурина...","Español, Castellano"
...,...,...,...,...,...
65,Чхаттисгархи,11 535 000,Индия,Индия,छत्तिसगढ़ी
66,Фула,11 428 700,Западная Африка,Западная Африка,"Pulaar, Fulfulde"
67,Дакхни[en],10 709 800,Индия,Индия,NaN
68,Малагасийский,10 484 000,Мадагаскар,Мадагаскар,Malagasy
69,Белорусский,10 200 000,Белоруссия,"Белоруссия, Польша",Беларуская мова

In [8]:
# сохранить dataframe с таблицей "Данные энциклопедии Encarta 2009 года" в csv
df.to_csv()

'№,Язык,Родной язык по версии Encarta[4],Средоточие,Территории распространения,Самоназвание(образец письменности)\n1,Китайский,1 212 560 000,Китай,"Китай, Тайвань, Сингапур, Малайзия","中文, 汉语"\n2,Арабский,422 039 637,,"страны Северной Африки, Саудовская Аравия, Ирак, Сирия, Йемен и др. страны Ближнего Востока",العربية\n3,Хинди,366 000 000,Индия,Индия,हिन्दी\n4,Английский,341 000 000,Англия,"Великобритания, США, Канада, Австралия, Новая Зеландия, Папуа — Новая Гвинея и многие другие страны Океании, Ирландия, Восточная Африка, Южная Африка, Нигерия, Гамбия, Гана, Сьерра-Леоне, Либерия, Гайана, Белиз, большинство стран Вест-Индии, Кипр, Мальта, Филиппины",English\n5,Испанский,322 200 637,Испания,"Испания, Южная Америка (кроме Бразилии, Суринама, Гайаны и Французской Гвианы), Мексика, Центральная Америка (кроме Белиза), Экваториальная Гвинея, Куба, Доминиканская Республика","Español, Castellano"\n6,Бенгальский,207 000 000,Бенгалия,"Бангладеш, Индия",বাংলা Bāṇlā\n7,Португальский,176 000 000,Португалия,"Португалия, Ангола, Бразилия, Гвинея-Бисау, Кабо-Верде, Мозамбик, Сан-Томе и Принсипи, Восточный Тимор, Макао",Português\n8,Русский,167 000 000,Россия,"Россия, Украина, Казахстан, Белоруссия, Литва, Латвия, Эстония, Абхазия, Киргизия, Молдавия, Южная Осетия, Таджикистан, Грузия, Армения, Азербайджан, Туркменистан, Узбекистан, Германия, Израиль и другие страны",Русский язык\n9,Японский,125 000 000,Япония,Япония,日本語\n10,Немецкий,100 130 000,Германия,"Германия, Австрия, Швейцария, Люксембург, Лихтенштейн, Бельгия",Deutsch\n11,Корейский,78 000 000,Корея,"Республика Корея, КНДР, КНР, США, Япония","한국어, 조선말"\n12,Французский,78 000 000,Франция,"Франция, Монако, Люксембург, Бельгия, Швейцария, Италия (Валле-д’Аоста), Канада (провинция Квебек), Западная и Центральная Африка, Джибути, Тунис, Коморские Острова, Вануату, США (Луизиана)",Français\n13,Яванский,75 567 550,Индонезия,Индонезия,"Basa Jawa, Basa Jawi"\n14,Телугу,69 666 000,Индия,Индия,తెలుగు\n15,Маратхи,68 022 000,Индия,Индия,मराठी\n16,Вьетнамский,68 000 000,Вьетнам,"Вьетнам, США, Камбоджа, Франция",Tiếng Việt\n17,Тамильский,66 000 000,Индия,"Индия, Шри-Ланка, Сингапур, Малайзия",தமிழ்\n18,Итальянский,62 000 000,Италия,"Италия, Сан-Марино, Ватикан, Швейцария (Тичино)",Italiano\n19,Турецкий,61 000 000,Турция,"Турция, Германия, Болгария, Кипр",Türk dili (Türkçe)\n20,Урду,60 290 000,Пакистан,"Пакистан, Индия","اردو, Urdu"\n21,Панджаби,57 129 000,Пакистан,"Пакистан, Индия","ਪੰਜਾਬੀ, پنجابی"\n22,Украинский,47 000 000,Украина,"Украина, Молдавия, США, Канада, Польша, Россия, Румыния, Словакия",Українська мова\n23,Гуджарати,46 100 000,Индия,Индия,ગુજરાતી\n24,Тайский,46 050 000,Таиланд,Таиланд,ภาษาไทย\n25,Польский,44 000 000,Польша,"Польша, Литва, Белоруссия","język polski, polszczyzna"\n26,Малаялам,35 706 000,Индия,Индия,മലയാളം\n27,Каннада,35 346 000,Индия,Индия,ಕನ್ನಡ\n28,Ория,32 300 000,Индия,Индия,ଓଡ଼ିଆ\n29,Бирманский,32 250 000,Мьянма,Мьянма (Бирма),ဗမာစာ\n30,Азербайджанский,31 423 000,Азербайджан,"Иран, Азербайджан, Россия (Дагестан), Турция, Грузия, Ирак (туркоманы)","Azərbaycan dili, Azərbaycan türkcəsi, Türk dili, Azəri."\n31,Персидский,31 280 000,Иран,"Иран, Афганистан, Таджикистан, Узбекистан",فارسی\n32,Сунданский,27 000 000,Индонезия,Индонезия,Basa Sunda\n33,Пушту,26 811 657,Афганистан,Афганистан,پښتو\n34,Румынский,26 265 555,Румыния,"Румыния, Молдавия, Украина",Limba română\n35,Бходжпури,26 254 000,Индия,Индия,भोजपुरी\n36,Хауса,24 200 000,Западная Африка,Западная Африка,Hausa / هَوُس (до 1930-х годов)\n37,Майтхили,24 191 900,Индия,Индия,मैथिली\n39,Сербохорватский,21 000 000,"Сербия, Хорватия,",бывшая Югославия (кроме Словении и Северной Македонии),"Српскохрватски језик, Srpskohrvatski jezik"\n40,Авадхи,20 540 000,Индия,Индия,अवधी\n41,Узбекский,20 051 000,Узбекистан,"Узбекистан, Афганистан, Таджикистан, Киргизия, Туркменистан, Казахстан, Россия","O‘zbek tili, Ўзбек тили, ئۇزبېك تیلى"\n42,Йоруба,20 000 000,Нигерия,Нигерия,Yorùbá\n43,Нидерландский,20 000 000,Нидерланды,"Нидерланды, Бельгия, Суринам",Nederlands\n44,Синдхи,19 720 000,Пакистан,Пакистан,सिन्धी / سنڌي\n45,Игбо,18 000 000,Нигерия,Нигерия,Igbo\n46,Амхарский,17 413 000,Эфиопия,Эфиопия,አማርኛ\n47,Оромо,17 232 000,Эфиопия,Эфиопия,Afaan Oromoo\n48,Индонезийский,17 070 000,Индонезия,Индонезия,Bahasa Indonesia\n49,Тагальский,17 000 000,Филиппины,Филиппины,Tagalog\n50,Непальский,16 056 000,Непал,Непал,नेपाली\n51,Ассамский,15 374 000,Индия,Индия,অসমিয়া\n52,Сараики,15 059 000,Пакистан,Пакистан,"سرائیکی, ਸਰਾਇਕੀ, सराइकी"\n53,Себуанский,15 000 000,Филиппины,Филиппины,Sugboanon\n54,Венгерский,14 500 000,Венгрия,"Венгрия, Румыния, Украина",Magyar nyelv\n55,Читтагонг,14 000 000,Бангладеш,Бангладеш,চাটগাঁইয়া বুলি\n56,Чжуанский,14 000 000,Китай,КНР,Sawcuengh\n57,Шона,14 000 000,Зимбабве,Зимбабве,Shona (chiShona)\n58,Мадурский,13 694 000,Индонезия,Индонезия,Basa Mathura\n59,Сингальский,13 220 000,Шри-Ланка,Шри-Ланка,සිංහල\n60,Марвари,13 183 000,Индия,Индия,मारवाड़ी\n61,Магахи,13 000 000,Индия,Индия,मगही\n62,Харьянви,13 000 000,Индия,Индия,हरियाणवी\n63,Греческий,12 000 000,Греция,"Греция, Кипр",Ελληνικά\n64,Чешский,12 000 000,Чехия,Чехия,"Čeština, Česky"\n65,Чхаттисгархи,11 535 000,Индия,Индия,छत्तिसगढ़ी\n66,Фула,11 428 700,Западная Африка,Западная Африка,"Pulaar, Fulfulde"\n67,Дакхни[en],10 709 800,Индия,Индия,\n68,Малагасийский,10 484 000,Мадагаскар,Мадагаскар,Malagasy\n69,Белорусский,10 200 000,Белоруссия,"Белоруссия, Польша",Беларуская мова\n'

In [9]:
# вывести первые 20 строк
df.head(12)

,Язык,Родной язык по версии Encarta[4],Средоточие,Территории распространения,Самоназвание(образец письменности)
№,,,,,
1,Китайский,1 212 560 000,Китай,"Китай, Тайвань, Сингапур, Малайзия","中文, 汉语"
2,Арабский,422 039 637,NaN,"страны Северной Африки, Саудовская Аравия, Ира...",العربية
3,Хинди,366 000 000,Индия,Индия,हिन्दी
4,Английский,341 000 000,Англия,"Великобритания, США, Канада, Австралия, Новая ...",English
5,Испанский,322 200 637,Испания,"Испания, Южная Америка (кроме Бразилии, Сурина...","Español, Castellano"
6,Бенгальский,207 000 000,Бенгалия,"Бангладеш, Индия",বাংলা Bāṇlā
7,Португальский,176 000 000,Португалия,"Португалия, Ангола, Бразилия, Гвинея-Бисау, Ка...",Português
8,Русский,167 000 000,Россия,"Россия, Украина, Казахстан, Белоруссия, Литва,...",Русский язык
9,Японский,125 000 000,Япония,Япония,日本語
10,Немецкий,100 130 000,Германия,"Германия, Австрия, Швейцария, Люксембург, Лихт...",Deutsch
11,Корейский,78 000 000,Корея,"Республика Корея, КНДР, КНР, США, Япония","한국어, 조선말"
12,Французский,78 000 000,Франция,"Франция, Монако, Люксембург, Бельгия, Швейцари...",Français

In [10]:
# вывести последние 7 строк
df.tail(7)

,Язык,Родной язык по версии Encarta[4],Средоточие,Территории распространения,Самоназвание(образец письменности)
№,,,,,
63,Греческий,12 000 000,Греция,"Греция, Кипр",Ελληνικά
64,Чешский,12 000 000,Чехия,Чехия,"Čeština, Česky"
65,Чхаттисгархи,11 535 000,Индия,Индия,छत्तिसगढ़ी
66,Фула,11 428 700,Западная Африка,Западная Африка,"Pulaar, Fulfulde"
67,Дакхни[en],10 709 800,Индия,Индия,NaN
68,Малагасийский,10 484 000,Мадагаскар,Мадагаскар,Malagasy
69,Белорусский,10 200 000,Белоруссия,"Белоруссия, Польша",Беларуская мова

In [11]:
# вывести список индексов
df.index

Int64Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
            18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
            35, 36, 37, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
            53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
            69],
           dtype='int64', name='№')

In [12]:
# вывести список значений колонки Язык
df['Язык'].values.tolist()

['Китайский',
 'Арабский',
 'Хинди',
 'Английский',
 'Испанский',
 'Бенгальский',
 'Португальский',
 'Русский',
 'Японский',
 'Немецкий',
 'Корейский',
 'Французский',
 'Яванский',
 'Телугу',
 'Маратхи',
 'Вьетнамский',
 'Тамильский',
 'Итальянский',
 'Турецкий',
 'Урду',
 'Панджаби',
 'Украинский',
 'Гуджарати',
 'Тайский',
 'Польский',
 'Малаялам',
 'Каннада',
 'Ория',
 'Бирманский',
 'Азербайджанский',
 'Персидский',
 'Сунданский',
 'Пушту',
 'Румынский',
 'Бходжпури',
 'Хауса',
 'Майтхили',
 'Сербохорватский',
 'Авадхи',
 'Узбекский',
 'Йоруба',
 'Нидерландский',
 'Синдхи',
 'Игбо',
 'Амхарский',
 'Оромо',
 'Индонезийский',
 'Тагальский',
 'Непальский',
 'Ассамский',
 'Сараики',
 'Себуанский',
 'Венгерский',
 'Читтагонг',
 'Чжуанский',
 'Шона',
 'Мадурский',
 'Сингальский',
 'Марвари',
 'Магахи',
 'Харьянви',
 'Греческий',
 'Чешский',
 'Чхаттисгархи',
 'Фула',
 'Дакхни[en]',
 'Малагасийский',
 'Белорусский']

In [13]:
# вывести список наименований колонок
df.columns

Index(['Язык', 'Родной язык по версии Encarta[4]', 'Средоточие',
       'Территории распространения', 'Самоназвание(образец письменности)'],
      dtype='object')

In [14]:
# вывести строку с индексом равным 68=Малагасийский
# (доступ по метке)
df.loc[68]

Язык                                  Малагасийский
Родной язык по версии Encarta[4]         10 484 000
Средоточие                               Мадагаскар
Территории распространения               Мадагаскар
Самоназвание(образец письменности)         Malagasy
Name: 68, dtype: object

In [15]:
# вывести строку с индексом равным 68=Малагасийский
# (доступ по числовому значению)
df.iloc[66]

Язык                                  Малагасийский
Родной язык по версии Encarta[4]         10 484 000
Средоточие                               Мадагаскар
Территории распространения               Мадагаскар
Самоназвание(образец письменности)         Malagasy
Name: 68, dtype: object

In [16]:
# вывести dataframe отфильтрованный по условию:
# значение колонки "Средоточие" == "Индия"
df[df["Средоточие"] == "Индия"]

,Язык,Родной язык по версии Encarta[4],Средоточие,Территории распространения,Самоназвание(образец письменности)
№,,,,,
3,Хинди,366 000 000,Индия,Индия,हिन्दी
14,Телугу,69 666 000,Индия,Индия,తెలుగు
15,Маратхи,68 022 000,Индия,Индия,मराठी
17,Тамильский,66 000 000,Индия,"Индия, Шри-Ланка, Сингапур, Малайзия",தமிழ்
23,Гуджарати,46 100 000,Индия,Индия,ગુજરાતી
26,Малаялам,35 706 000,Индия,Индия,മലയാളം
27,Каннада,35 346 000,Индия,Индия,ಕನ್ನಡ
28,Ория,32 300 000,Индия,Индия,ଓଡ଼ିଆ
35,Бходжпури,26 254 000,Индия,Индия,भोजपुरी
37,Майтхили,24 191 900,Индия,Индия,मैथिली
40,Авадхи,20 540 000,Индия,Индия,अवधी
51,Ассамский,15 374 000,Индия,Индия,অসমিয়া
60,Марвари,13 183 000,Индия,Индия,मारवाड़ी
61,Магахи,13 000 000,Индия,Индия,मगही
62,Харьянви,13 000 000,Индия,Индия,हरियाणवी
65,Чхаттисгархи,11 535 000,Индия,Индия,छत्तिसगढ़ी
67,Дакхни[en],10 709 800,Индия,Индия,NaN

In [17]:
# вывести количество уникальных значений в колонке "Средоточие"
df["Средоточие"].nunique()

40

In [18]:
# вывести все уникальные значения в колонке "Средоточие" (тип list)
df["Средоточие"].unique()

array(['Китай', nan, 'Индия', 'Англия', 'Испания', 'Бенгалия',
       'Португалия', 'Россия', 'Япония', 'Германия', 'Корея', 'Франция',
       'Индонезия', 'Вьетнам', 'Италия', 'Турция', 'Пакистан', 'Украина',
       'Таиланд', 'Польша', 'Мьянма', 'Азербайджан', 'Иран', 'Афганистан',
       'Румыния', 'Западная Африка', 'Сербия, Хорватия,', 'Узбекистан',
       'Нигерия', 'Нидерланды', 'Эфиопия', 'Филиппины', 'Непал',
       'Венгрия', 'Бангладеш', 'Зимбабве', 'Шри-Ланка', 'Греция', 'Чехия',
       'Мадагаскар', 'Белоруссия'], dtype=object)

In [19]:
# переименовать колонку "Родной язык по версии Encarta[4]" на "Родной язык"
df.rename(columns={'Родной язык по версии Encarta[4]': 'Родной язык'}, inplace=True)

# вывести список наименований колонок в датафрейме
df.columns

Index(['Язык', 'Родной язык', 'Средоточие', 'Территории распространения',
       'Самоназвание(образец письменности)'],
      dtype='object')

In [20]:
# вывести минимальное значение из колонки "Родной язык"
df["Родной язык"].min()

'1 212 560 000'

In [21]:
# вывести максимальное значение из колонки "Родной язык"
df["Родной язык"].max()

'78 000 000'